version: "3.7"
services:

  app-postgres:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456

  app-pgadmin:
    image: dpage/pgadmin4
    ports:
      - "15432:80"
    networks:
      - postgres-network
    environment:
        PGADMIN_DEFAULT_EMAIL: dellean.santos@gmail.com
        PGADMIN_DEFAULT_PASSWORD: 123456


networks:
  postgres-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local